import Head from 'next/head';
import Hero from '@/components/hero';
import AboutHome from '@/components/about-home';
import ImgText from '@/components/img-text';
import HorizontalSection from '@/components/horizontal-section';
import MeetHome from '@/components/meet-home';


export default function Home() {
  

  const contentHero = {
    type: 'principal',
    title: 'Welcome To Your New “Happy Place”',
    subtitle: 'Custom-Crafted & Private Journeys To Enchanting Colombia',
  };


  const imgTextBlocks = [
    {
      content: {
        img: '/images/home/08.jpg',
        text: ['With our deep roots in Colombia, our travel designers can craft travel experiences that awe you at every turn, from the colorful colonial architecture of Cartagena to the brilliant blue waters of Colombia`s Caribbean coast.']
      },
      invert: false
    },
    {
      content: {
        img: '/images/home/14-b.jpg',
        text: ['Venture deep into jungles, forests, mountain-top villages, and cosmopolitan cities, with the help of our expert local guides who’ll pamper you all along the way.']
      },
      invert: true
    }
  ]


  return (
    <>
      <Head>
        <title>Colombian Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero contentHero={contentHero} />
      <AboutHome />
      {imgTextBlocks.map((data, i) => (
        <ImgText key={typeof window !== 'undefined' ? window.crypto.randomUUID() : i} data={data}/>        
      ))}
      <HorizontalSection horizontalType={'home'}/>
      <MeetHome />
    </>
  );
}
