import Head from 'next/head';
import Hero from '@/components/hero';
import AboutHome from '@/components/about-home';
import ImgText from '@/components/img-text';
import HorizontalSection from '@/components/horizontal-section';
import MeetHome from '@/components/meet-home';

function Home({ homedata }) {
  console.log(homedata);

  const { hero, about, blockimages, horizontal_blocks, blogsection } =
    homedata.home_data;

  return (
    <>
      <Head>
        <title>Colombian Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero contentHero={hero} />
      <AboutHome aboutHome={about} />
      {blockimages.map((data, i) => (
        <ImgText
          key={typeof window !== 'undefined' ? window.crypto.randomUUID() : i}
          data={data}
        />
      ))}
      <HorizontalSection
        horizontalType={'home'}
        horizontalData={horizontal_blocks}
      />
      <MeetHome blogdata={blogsection} />
    </>
  );
}

export async function getStaticProps() {
  const resHome = await fetch(
    `${process.env.NEXT_PUBLIC_ENDPOINT_CONTENT}colombian-app/v1/home`
  );
  const homedata = await resHome.json();
  return {
    props: { homedata },
  };
}

export default Home;
