import Head from 'next/head';
import Hero from '@/components/hero';
import AboutHome from '@/components/about-home';
import ImgText from '@/components/img-text';
import HorizontalSection from '@/components/horizontal-section';
import MeetHome from '@/components/meet-home';


export default function Home({homedata}) {
  
  console.log(homedata);

  const contentHero = homedata.home_data.hero;
  const aboutHome = homedata.home_data.about;
  const imgTextBlocks = homedata.home_data.blockimages;
  const horizontalBlocks = homedata.home_data.horizontal_blocks;

  return (
    <>
      <Head>
        <title>Colombian Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero contentHero={contentHero} />
      <AboutHome aboutHome={aboutHome} />
      {imgTextBlocks.map((data, i) => (
        <ImgText key={typeof window !== 'undefined' ? window.crypto.randomUUID() : i} data={data}/>        
      ))}
      <HorizontalSection horizontalType={'home'} horizontalData={horizontalBlocks}/>
      <MeetHome />
    </>
  );
}

export async function getServerSideProps() {
  const resHome = await fetch(`https://paperplane.com.co/dev/colombiantrip/wp/wp-json/colombian-app/v1/home`)
  const homedata = await resHome.json()
  return { props: { homedata } }
}

